# Site settings

title: Federal Public Key Infrastructure Guides
name: Federal Public Key Infrastructure Guides
email: fpki@gsa.gov
author:
    name: FICAM
description: Information on the US Federal Public Key Infrastructure (FPKI)
highlighter: rouge
repo_url: https://github.com/GSA/fpki-guides
baseurl: '/fpki-guides'
branch: federalist-pages
# Federalist overwrites the site.branch value when deploying
# the site.branch was used in dynamic link generation for objects like Edit Page
# we want the dynamic links to send users to the staging branch.  Adding new site variable to ensure federalist doesn't overwrite.
editbranch: staging

# theme: uswds-jekyll
search_site_handle: idmprod

system_notification_url: http%3A%2F%2Fgithub.com%2FGSA%2Ffpki-guides%2Fissues%2Fnew%3Ftitle%3DSystem%20Notification%20for%3A%20%3CYour%20Organization%3E%26amp%3Bbody%3D%23%23%23%23%20notice_date%3A%20%0A%0A%3Cie%2C%2007%2F21%2F2017%2015%3A34%20EST%20%3E%0A%0A%23%23%23%23%20change_type%3A%0A%0A%20%3Cie%2C%20CA%20Certificate%20Issuance%20%3E%0A%0A%23%23%23%23%20start_datetime%3A%20%0A%0A%3Cie%2C%20%2007%2F21%2F2017%2015%3A34%20EST%20%3E%0A%0A%23%23%23%23%20end_datetime%3A%0A%0A%20%20%3Cie%2C%2007%2F21%2F2017%2015%3A34%20EST%20%3E%0A%0A%23%23%23%23%20system%3A%0A%0A%20%3Cie%2C%20Federal%20Bridge%20CA%202016%20%3E%0A%0A%23%23%23%23%20change_description%3A%20%0A%0A%3Cie%2C%20sample%20change_description%20%20%3E%0A%0A%23%23%23%23%20impact%3A%0A%0A%20%3Cie%2C%20sample%20non%20impact%20%3E%0A%0A%23%23%23%23%20contact%3A%0A%0A%20%3Cie%2C%20sampleuser%40sampleagency.gov%20%3E%0A%0A%23%23%23%23%20ca_certificate_hash%3A%0A%0A%20%3Cie%2C%20SHA256%3E%0A%0A%23%23%23%23%20ca_certificate_issuer%3A%0A%20%0A%3Cie%2C%20Federal%20Bridge%20CA%202016%20%3E%0A%0A%23%23%23%23%20ca_certificate_subject%3A%0A%20%0A%3Cie%2C%20john%20Dou%3E%0A%0A%23%23%23%23%20cdp_uri%3A%0A%20%0A%3Cie%2C%20http%3A%2F%2Fpki.treas.gov%2Fdhsca4.crl%3E%0A%0A%23%23%23%23%20aia_uri%3A%0A%20%0A%3Cie%2C%20http%3A%2F%2Fpki.treas.gov%2Fsample.p7b%3E%0A%0A%23%23%23%23%20sia_uri%3A%0A%20%0A%3Cie%2C%20http%3A%2F%2Fpki.treas.gov%2Fsample.p7b%3E%0A%0A%23%23%23%23%20ocsp_uri%3A%0A%20%0A%3Cie%2C%20http%3A%2F%2Fpki.treas.gov%2Fdhsca4.crl%3E%20
# Links
# List links that you would like to appear on the top navigation bar here
navbar:
- title: IDmanagement.gov
  description: Idmanagement.gov
  url: https://www.idmanagement.gov
- title: Federal ICAM Architecture
  description: Federal ICAM Architecture
  url: https://arch.idmanagement.gov
- title: PIV Guides
  description: PIV Guides
  url: https://piv.idmanagement.gov
#- title: Federal PKI Guides
#  description: Federal PKI Guides
#  url: https://github.com/gsa/fpki-guides
- title: Physical Access Control Guide
  description: Physical Access Control Guides
  url: https://pacs.idmanagement.gov
- title: Program Management Guide
  description: Program Management Guide
  url: https://pm.idmanagement.gov

# Build settings
markdown: kramdown

#kramdown:
#  input: GFM
# syntax_highlighter: rouge

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Certification Authorities
  url: ca
  internal: true
  coll: false
- text: Certificates and CRLs
  url: crls/
  internal: true
  coll: true
  collname: crls
# - text: Certificate Policies
  # url: policyobjects
  # internal: true
  # coll: false
- text: Trust Stores
  url: truststores/
  internal: true
  coll: true
  collname: truststores
- text: Useful Tools
  url: tools/
  internal: true
  coll: true
  collname: tools
- text: Announcements
  url: announcements/
  internal: true
  coll: true
  collname: announcements
- text: System Notifications
  url: notifications
  internal: true
  coll: false
#https://github.com/jekyll/jekyll/issues/2346
#- text: Engineer Guides
# url: engineer/
# internal: true
# coll: true
# collname: engineer
#- text: FAQ
#  url: faq
#  internal: true
#  coll: true
#  collname: faq
#- text: About PKI
#  url: pki
#  internal: true
#  coll: false
#  collname: pkifundamentals
#- text: Glossary
#  url: glossary
#  internal: true
#  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false



#https://github.com/jekyll/jekyll/issues/2346
collections:
  engineer:
    label: "Engineer Guides"
    permalink: /engineer/:path/
    output: true
#  pkifundamentals:
#    label: "Public Key Infrastructure"
#    permalink: /pki/:path/
#    output: true
  faq:
    label: "FAQ"
    permalink: /faq/:path/
    output: true
  crls:
    label: "Certificates and CRLs"
    permalink: /crls/:path/
    output: true
  truststores:
    label: "Trust Stores"
    permalink: /truststores/:path/
    output: true
  tools:
    label: "Useful Tools"
    permalink: /tools/:path/
    output: true
  announcements:
    label: "Announcements"
    permalink: /announcements/:path/
    output: true

include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
